
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Malu Passo Silva
 */
import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.SQLException;

public class Turma extends javax.swing.JFrame {

    Conexao con_cliente;
    
    public Turma() {
        
        con_cliente = new Conexao();
        con_cliente.conecta();
        con_cliente.executaSQL("select * from turma order by IdTurma"); 
        
        initComponents();
        
        turma.setAutoCreateRowSorter(true);
        preencherTabela();
        posicionarRegistro();
    }
    
    public void preencherTabela(){
        
        turma.getColumnModel().getColumn(0).setPreferredWidth(70);
        turma.getColumnModel().getColumn(1).setPreferredWidth(70);
        turma.getColumnModel().getColumn(2).setPreferredWidth(70);
        turma.getColumnModel().getColumn(3).setPreferredWidth(70);
        
        DefaultTableModel modelo = (DefaultTableModel) turma.getModel();
        modelo.setNumRows(0);
        
        try{
            
            con_cliente.resultset.beforeFirst();
            
            while(con_cliente.resultset.next()){
                
                modelo.addRow(new Object[]{
                    
                    con_cliente.resultset.getString("IdTurma"), con_cliente.resultset.getString("QtdAlunos"), 
                    con_cliente.resultset.getString("IdProfessor"),con_cliente.resultset.getString("IdCurso")
                        
                });
                       
            }
              
        }
          
        catch(SQLException erro){
                
            JOptionPane.showMessageDialog(null, "\n Erro ao listar dados da tabela!! :\n" + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);    
                
        }   
            
    }
    
    public void posicionarRegistro(){
        
        try{
            
            con_cliente.resultset.first();
            mostrar_Dados();
            
        }
        
        catch(SQLException erro){
            
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    public void mostrar_Dados(){
        
        try{
            
            txtCod.setText(con_cliente.resultset.getString("IdTurma"));
            txtQtd.setText(con_cliente.resultset.getString("QtdAlunos"));
            txtProf.setText(con_cliente.resultset.getString("IdProfessor"));
            //txtAl.setText(con_cliente.resultset.getString("IdAluno"));
            txtCurso.setText(con_cliente.resultset.getString("IdCurso"));
            
        }
        
        catch(SQLException erro){
            
            //JOptionPane.showMessageDialog(null, "Não localizou dados: "+erro, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back_btn = new javax.swing.JLabel();
        title_lbl = new javax.swing.JLabel();
        img_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qtd_lbl = new javax.swing.JLabel();
        idprof_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        turma = new javax.swing.JTable();
        txtCod = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        txtProf = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        PrimeiroRegistro = new javax.swing.JLabel();
        VoltarUmRegistro = new javax.swing.JLabel();
        ProximoRegistro = new javax.swing.JLabel();
        UltimoRegistro = new javax.swing.JLabel();
        criar_btn = new javax.swing.JLabel();
        edit_btn = new javax.swing.JLabel();
        save_btn = new javax.swing.JLabel();
        Delete_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        back_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fasticon-Essential-Toolbar-Undo.32.png"))); // NOI18N
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        title_lbl.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        title_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_lbl.setText("Turma");

        img_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chalkboard.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel1.setText("Código:");

        qtd_lbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        qtd_lbl.setText("Quantidade de alunos:");

        idprof_lbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        idprof_lbl.setText("ID do professor:");

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel2.setText("ID do curso:");

        turma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Qtd. de alunos", "ID do professor", "ID do curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        turma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turmaMouseClicked(evt);
            }
        });
        turma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                turmaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(turma);
        if (turma.getColumnModel().getColumnCount() > 0) {
            turma.getColumnModel().getColumn(0).setResizable(false);
            turma.getColumnModel().getColumn(1).setResizable(false);
            turma.getColumnModel().getColumn(2).setResizable(false);
            turma.getColumnModel().getColumn(3).setResizable(false);
        }

        txtCod.setEditable(false);
        txtCod.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        txtQtd.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        txtProf.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        txtCurso.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        PrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-rew.48.png"))); // NOI18N
        PrimeiroRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrimeiroRegistroMouseClicked(evt);
            }
        });

        VoltarUmRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoltarUmRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-back.48.png"))); // NOI18N
        VoltarUmRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarUmRegistroMouseClicked(evt);
            }
        });

        ProximoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProximoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-fordward.48.png"))); // NOI18N
        ProximoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProximoRegistroMouseClicked(evt);
            }
        });

        UltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-ff.48.png"))); // NOI18N
        UltimoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UltimoRegistroMouseClicked(evt);
            }
        });

        criar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Badge-plus.48.png"))); // NOI18N
        criar_btn.setToolTipText("Criar um novo registro");
        criar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criar_btnMouseClicked(evt);
            }
        });

        edit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Pencil-yellow.48.png"))); // NOI18N
        edit_btn.setToolTipText("Editar o registro");
        edit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_btnMouseClicked(evt);
            }
        });

        save_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Floppy-disk.48.png"))); // NOI18N
        save_btn.setToolTipText("Salvar registro");
        save_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_btnMouseClicked(evt);
            }
        });

        Delete_btn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Creative-Freedom-Free-Funktional-02-Recycle.48.png"))); // NOI18N
        Delete_btn.setToolTipText("Deletar registro");
        Delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(img_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(qtd_lbl)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtQtd))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(idprof_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtProf)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PrimeiroRegistro)
                                        .addGap(18, 18, 18)
                                        .addComponent(VoltarUmRegistro)
                                        .addGap(18, 18, 18)
                                        .addComponent(ProximoRegistro)
                                        .addGap(18, 18, 18)
                                        .addComponent(UltimoRegistro)
                                        .addGap(71, 71, 71)
                                        .addComponent(criar_btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(save_btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(title_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_lbl)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtd_lbl)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idprof_lbl)
                            .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(img_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrimeiroRegistro)
                            .addComponent(ProximoRegistro)
                            .addComponent(UltimoRegistro)
                            .addComponent(criar_btn)
                            .addComponent(edit_btn)
                            .addComponent(save_btn)
                            .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VoltarUmRegistro))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        
        //Abrir a tela do curso e fechar a tela de menu.
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_back_btnMouseClicked

    private void PrimeiroRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrimeiroRegistroMouseClicked
        
        try{
            con_cliente.resultset.first();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_PrimeiroRegistroMouseClicked

    private void ProximoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProximoRegistroMouseClicked
        
        try{
            con_cliente.resultset.next();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_ProximoRegistroMouseClicked

    private void UltimoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UltimoRegistroMouseClicked
        
        try{
            con_cliente.resultset.last();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_UltimoRegistroMouseClicked

    private void VoltarUmRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarUmRegistroMouseClicked
        
        try{
            con_cliente.resultset.previous();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o registro anterior: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_VoltarUmRegistroMouseClicked

    private void criar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criar_btnMouseClicked

        //Limpa as caixas de texto
        txtCod.setText("");
        txtQtd.setText("");
        txtProf.setText("");
        txtCurso.setText("");

    }//GEN-LAST:event_criar_btnMouseClicked

    private void edit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_btnMouseClicked

        //Criando strings para armazenar os dados digitados nos campos de texto
        String codigo = txtCod.getText();
        String quantidade = txtQtd.getText();
        String prof = txtProf.getText();
        String curso = txtCurso.getText();

        //
        String sql = "";

        //
        String msg = "";

        try{

            if(txtCod.getText().equals("")){

                sql = "insert into turma (QtdAlunos, IdProfessor, IdCurso) values (" + quantidade
                + "', '" + prof + "', '" + curso + "' where IdTurma = " + txtCod.getText();

                msg = "Gravação de um novo registro";

            }

            else{

                sql = "update turma set QtdAlunos = '" + quantidade + "', IdProfessor = '" + prof + "', IdCurso = '" + curso + 
                "' where IdTurma = " + txtCod.getText();

                msg = "Alteração de registro ";

            }

            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, msg + "realizada com sucesso!", "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);

            con_cliente.executaSQL("select * from turma order by IdTurma");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();
        }

        catch(SQLException errosql){

            //JOptionPane.showMessageDialog(null, "Erro de gravação :\n " + errosql, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_edit_btnMouseClicked

    private void save_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_btnMouseClicked

        //Criando strings para armazenar os dados digitados nos campos de texto
        String quantidade = txtQtd.getText();
        String prof = txtProf.getText();
        String curso = txtCurso.getText();
        
        //
        try{

            String insert_sql = "insert into turma (QtdAlunos, IdProfessor, IdCurso) values ('" + quantidade + "', '" + prof + "', '" + curso + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from turma order by IdTurma");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();

        }

        catch(SQLException errosql){

            JOptionPane.showMessageDialog(null, "Erro de gravação :\n " + errosql, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_save_btnMouseClicked

    private void Delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_btnMouseClicked

        String sql = "";

        try{

            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar exclusão", JOptionPane.YES_NO_OPTION, 3);

            if(resposta == 0){

                sql = "delete from turma where IdTurma = " + txtCod.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);

                if(excluir == 1){

                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from turma order by IdTurma");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();

                }

                else{

                    JOptionPane.showMessageDialog(null, "Operação cancela pelo usuário!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        }

        catch(SQLException excecao){

            JOptionPane.showMessageDialog(null, "Erro na exclusão: "  + excecao, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_Delete_btnMouseClicked

    private void turmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turmaMouseClicked
        ///Evento para o clique do mouse sobre o registro da tabela:
        int linha_selecionada = turma.getSelectedRow();
        txtCod.setText(turma.getValueAt(linha_selecionada, 0).toString());
        txtQtd.setText(turma.getValueAt(linha_selecionada, 1).toString());
        txtProf.setText(turma.getValueAt(linha_selecionada, 2).toString());
        txtCurso.setText(turma.getValueAt(linha_selecionada, 3).toString());
    }//GEN-LAST:event_turmaMouseClicked

    private void turmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_turmaKeyPressed
        //Evento para o clique do mouse sobre o registro da tabela:
        int linha_selecionada = turma.getSelectedRow();
        txtCod.setText(turma.getValueAt(linha_selecionada, 0).toString());
        txtQtd.setText(turma.getValueAt(linha_selecionada, 1).toString());
        txtProf.setText(turma.getValueAt(linha_selecionada, 2).toString());
        txtCurso.setText(turma.getValueAt(linha_selecionada, 3).toString());
    }//GEN-LAST:event_turmaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete_btn;
    private javax.swing.JLabel PrimeiroRegistro;
    private javax.swing.JLabel ProximoRegistro;
    private javax.swing.JLabel UltimoRegistro;
    private javax.swing.JLabel VoltarUmRegistro;
    private javax.swing.JLabel back_btn;
    private javax.swing.JLabel criar_btn;
    private javax.swing.JLabel edit_btn;
    private javax.swing.JLabel idprof_lbl;
    private javax.swing.JLabel img_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel qtd_lbl;
    private javax.swing.JLabel save_btn;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JTable turma;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
