/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Malu Passo Silva
 */
import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.SQLException;

public class Curso extends javax.swing.JFrame {

    Conexao con_cliente;
    
    public Curso() {
        
        con_cliente = new Conexao();
        con_cliente.conecta();
        con_cliente.executaSQL("select * from curso order by IdCurso"); 
        
        initComponents();
        
        curso.setAutoCreateRowSorter(true);
        preencherTabela();
        posicionarRegistro();
    }

    public void preencherTabela(){
        
        curso.getColumnModel().getColumn(0).setPreferredWidth(70);
        curso.getColumnModel().getColumn(1).setPreferredWidth(70);
        curso.getColumnModel().getColumn(2).setPreferredWidth(70);
        curso.getColumnModel().getColumn(3).setPreferredWidth(70);
        curso.getColumnModel().getColumn(4).setPreferredWidth(70);
        curso.getColumnModel().getColumn(5).setPreferredWidth(70);
        curso.getColumnModel().getColumn(6).setPreferredWidth(70);
        
        DefaultTableModel modelo = (DefaultTableModel) curso.getModel();
        modelo.setNumRows(0);
        
        try{
            
            con_cliente.resultset.beforeFirst();
            
            while(con_cliente.resultset.next()){
                
                modelo.addRow(new Object[]{
                    
                    con_cliente.resultset.getString("IdCurso"), con_cliente.resultset.getString("NomeCurso"), con_cliente.resultset.getString("QuantTurmas"),
                    con_cliente.resultset.getString("DataInicio"), con_cliente.resultset.getString("DataTermino"), con_cliente.resultset.getString("CargaHoraria"), 
                    con_cliente.resultset.getString("Preco")
                        
                });
                       
            }
              
        }
          
        catch(SQLException erro){
                
            JOptionPane.showMessageDialog(null, "\n Erro ao listar dados da tabela!! :\n" + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);    
                
        }   
            
    }
    
    public void posicionarRegistro(){
        
        try{
            
            con_cliente.resultset.first();
            mostrar_Dados();
            
        }
        
        catch(SQLException erro){
            
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    public void mostrar_Dados(){
        
        try{
            
            txtCod.setText(con_cliente.resultset.getString("IdCurso"));
            txtNC.setText(con_cliente.resultset.getString("NomeCurso"));
            txtQ.setText(con_cliente.resultset.getString("QuantTurmas"));
            txtDI.setText(con_cliente.resultset.getString("DataInicio"));
            txtDT.setText(con_cliente.resultset.getString("DataTermino"));
            txtCH.setText(con_cliente.resultset.getString("CargaHoraria"));
            txtP.setText(con_cliente.resultset.getString("Preco"));
            
            
        }
        
        catch(SQLException erro){
            
            JOptionPane.showMessageDialog(null, "Não localizou dados: "+erro, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backbtn = new javax.swing.JLabel();
        title_lbl = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        codlbl = new javax.swing.JLabel();
        nomelbl = new javax.swing.JLabel();
        qtdlbl = new javax.swing.JLabel();
        dtilbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chlbl = new javax.swing.JLabel();
        precolbl = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        PrimeiroRegistro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        curso = new javax.swing.JTable();
        txtNC = new javax.swing.JTextField();
        txtQ = new javax.swing.JTextField();
        txtDI = new javax.swing.JTextField();
        txtDT = new javax.swing.JTextField();
        txtCH = new javax.swing.JTextField();
        txtP = new javax.swing.JTextField();
        VoltarUmRegistro = new javax.swing.JLabel();
        ProximoRegistro = new javax.swing.JLabel();
        UltimoRegistro = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        create = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        backbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fasticon-Essential-Toolbar-Undo.32.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });

        title_lbl.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        title_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_lbl.setText("Curso");

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/online-education.png"))); // NOI18N

        codlbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        codlbl.setText("Código:");

        nomelbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        nomelbl.setText("Nome do curso:");

        qtdlbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        qtdlbl.setText("Quantidade de turmas:");

        dtilbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        dtilbl.setText("Data de início:");

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel1.setText("Data de término:");

        chlbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        chlbl.setText("Carga Horária:");

        precolbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        precolbl.setText("Preço:");

        txtCod.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtCod.setToolTipText("Inserir código");

        PrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-rew.48.png"))); // NOI18N
        PrimeiroRegistro.setToolTipText("Ir para o primeiro registro");
        PrimeiroRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrimeiroRegistroMouseClicked(evt);
            }
        });

        curso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome do curso", "Qtd. de turmas", "Data de início", "Data de término", "Carga Horária", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursoMouseClicked(evt);
            }
        });
        curso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cursoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(curso);
        if (curso.getColumnModel().getColumnCount() > 0) {
            curso.getColumnModel().getColumn(0).setResizable(false);
            curso.getColumnModel().getColumn(1).setResizable(false);
            curso.getColumnModel().getColumn(2).setResizable(false);
            curso.getColumnModel().getColumn(3).setResizable(false);
            curso.getColumnModel().getColumn(4).setResizable(false);
            curso.getColumnModel().getColumn(5).setResizable(false);
            curso.getColumnModel().getColumn(6).setResizable(false);
        }

        txtNC.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtNC.setToolTipText("Inserir nome do curso");

        txtQ.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtQ.setToolTipText("Inserir quantidade de turmas");

        txtDI.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtDI.setToolTipText("Inserir data de início");

        txtDT.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtDT.setToolTipText("Inserir data de término");

        txtCH.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtCH.setToolTipText("Inserir carga horária");

        txtP.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtP.setToolTipText("Inserir preço");

        VoltarUmRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-back.48.png"))); // NOI18N
        VoltarUmRegistro.setToolTipText("Voltar um registro");
        VoltarUmRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarUmRegistroMouseClicked(evt);
            }
        });

        ProximoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProximoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-fordward.48.png"))); // NOI18N
        ProximoRegistro.setToolTipText("Avançar um registro");
        ProximoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProximoRegistroMouseClicked(evt);
            }
        });

        UltimoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-ff.48.png"))); // NOI18N
        UltimoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UltimoRegistroMouseClicked(evt);
            }
        });

        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Creative-Freedom-Free-Funktional-02-Recycle.48.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Floppy-disk.48.png"))); // NOI18N
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Pencil-yellow.48.png"))); // NOI18N
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        create.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Badge-plus.48.png"))); // NOI18N
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(codlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCod))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(nomelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtNC))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(qtdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtQ))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(dtilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtDI))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtDT))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(chlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCH))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(precolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PrimeiroRegistro)
                                        .addGap(18, 18, 18)
                                        .addComponent(VoltarUmRegistro)
                                        .addGap(18, 18, 18)
                                        .addComponent(ProximoRegistro)
                                        .addGap(18, 18, 18)
                                        .addComponent(UltimoRegistro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                                        .addComponent(create)
                                        .addGap(18, 18, 18)
                                        .addComponent(edit)
                                        .addGap(28, 28, 28)
                                        .addComponent(save)
                                        .addGap(19, 19, 19)
                                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(31, 31, 31))
                    .addComponent(title_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbtn)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title_lbl)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codlbl)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nomelbl)
                                    .addComponent(txtNC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(qtdlbl)
                                    .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dtilbl)
                                    .addComponent(txtDI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chlbl))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precolbl)
                    .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VoltarUmRegistro)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProximoRegistro)
                            .addComponent(UltimoRegistro)
                            .addComponent(PrimeiroRegistro)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(delete)
                                .addComponent(save)
                                .addComponent(edit)
                                .addComponent(create)))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        
        //Abrir a tela do curso e fechar a tela de menu.
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_backbtnMouseClicked

    private void PrimeiroRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrimeiroRegistroMouseClicked
        
        try{
            con_cliente.resultset.first();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_PrimeiroRegistroMouseClicked

    private void VoltarUmRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarUmRegistroMouseClicked
        
        try{
            con_cliente.resultset.previous();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o registro anterior: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_VoltarUmRegistroMouseClicked

    private void ProximoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProximoRegistroMouseClicked
        
        try{
            con_cliente.resultset.next();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_ProximoRegistroMouseClicked

    private void UltimoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UltimoRegistroMouseClicked
        
        try{
            con_cliente.resultset.last();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_UltimoRegistroMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        
        String sql = "";
        
        try{
            
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar exclusão", JOptionPane.YES_NO_OPTION, 3);
            
            if(resposta == 0){
                
                sql = "delete from curso where IdCurso = " + txtCod.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                
                if(excluir == 1){
                    
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from curso order by IdCurso");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                    
                }
                
                else{
                    
                    JOptionPane.showMessageDialog(null, "Operação cancela pelo usuário!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    
                }
            }
        }
        
        catch(SQLException excecao){
            
            JOptionPane.showMessageDialog(null, "Erro na exclusão: "  + excecao, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        
        }
        
    }//GEN-LAST:event_deleteMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        
        //Criando strings para armazenar os dados digitados nos campos de texto
        String codigo = txtCod.getText();
        String nome = txtNC.getText();
        String qtd = txtQ.getText();
        String di = txtDI.getText();
        String dt = txtDT.getText();
        String ch = txtCH.getText();
        String p = txtP.getText();
        
        //
        try{
            
            String insert_sql = "insert into curso(IdCurso, NomeCurso, QuantTurmas, DataInicio, DataTermino, CargaHoraria, Preco) values ('" + 
            codigo + "', '" + nome + "', '" + qtd + "', '" + di + "', '" + dt + "', '" + ch + "', '" + p + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from curso order by IdCurso");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();
            
        }
        
        catch(SQLException errosql){
            
            JOptionPane.showMessageDialog(null, "Erro de gravação :\n " + errosql, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_saveMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        
        //Criando strings para armazenar os dados digitados nos campos de texto
        String nome = txtNC.getText();
        String qt = txtQ.getText();
        String di = txtDI.getText();
        String dt = txtDT.getText();
        String ch = txtCH.getText();
        String p = txtP.getText();

        //
        String sql = "";
        
        //
        String msg = "";
        
        try{
            
            if(txtCod.getText().equals("")){
                
                sql = "insert into curso (NomeCurso, QuantTurmas, DataInicio, DataTermino, CargaHoraria, Preco) values (" + nome 
                        + "', '" + qt + "', '" + di + "', '" + dt + "', '" +  ch + "', '" + p + "' where IdCurso = " + txtCod.getText();
                
                msg = "Gravação de um novo registro";
            
            }
            
            else{
                
                sql = "update curso set NomeCurso = '" + nome + "', QuantTurmas = '" + qt + "', DataInicio = '" + di + "', DataTermino = '" + dt
                        + "', CargaHoraria = '" + ch + "', Preco = '" + p + "' where IdCurso = " + txtCod.getText();
                
                msg = "Alteração de registro ";
            
            }
            
            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, msg + "realizada com sucesso!", "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
            
            con_cliente.executaSQL("select * from curso order by IdCurso");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();
        }
        
        catch(SQLException errosql){
            
            JOptionPane.showMessageDialog(null, "Erro de gravação :\n " + errosql, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_editMouseClicked

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        
        //Limpa as caixas de texto
        txtCod.setText("");
        txtNC.setText("");
        txtQ.setText("");
        txtDI.setText("");
        txtDT.setText("");
        txtCH.setText("");
        txtP.setText("");

    }//GEN-LAST:event_createMouseClicked

    private void cursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cursoKeyPressed
       
        //Evento para o clique do mouse sobre o registro da tabela:
        int linha_selecionada = curso.getSelectedRow();
        txtCod.setText(curso.getValueAt(linha_selecionada, 0).toString());
        txtNC.setText(curso.getValueAt(linha_selecionada, 1).toString());
        txtQ.setText(curso.getValueAt(linha_selecionada, 2).toString());
        txtDI.setText(curso.getValueAt(linha_selecionada, 3).toString());
        txtDT.setText(curso.getValueAt(linha_selecionada, 4).toString());
        txtCH.setText(curso.getValueAt(linha_selecionada, 5).toString());
        txtP.setText(curso.getValueAt(linha_selecionada, 6).toString());
        
    }//GEN-LAST:event_cursoKeyPressed

    private void cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursoMouseClicked
        
        //Evento para o clique do mouse sobre o registro da tabela:
        int linha_selecionada = curso.getSelectedRow();
        txtCod.setText(curso.getValueAt(linha_selecionada, 0).toString());
        txtNC.setText(curso.getValueAt(linha_selecionada, 1).toString());
        txtQ.setText(curso.getValueAt(linha_selecionada, 2).toString());
        txtDI.setText(curso.getValueAt(linha_selecionada, 3).toString());
        txtDT.setText(curso.getValueAt(linha_selecionada, 4).toString());
        txtCH.setText(curso.getValueAt(linha_selecionada, 5).toString());
        txtP.setText(curso.getValueAt(linha_selecionada, 6).toString());
        
    }//GEN-LAST:event_cursoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Curso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrimeiroRegistro;
    private javax.swing.JLabel ProximoRegistro;
    private javax.swing.JLabel UltimoRegistro;
    private javax.swing.JLabel VoltarUmRegistro;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel chlbl;
    private javax.swing.JLabel codlbl;
    private javax.swing.JLabel create;
    private javax.swing.JTable curso;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel dtilbl;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomelbl;
    private javax.swing.JLabel precolbl;
    private javax.swing.JLabel qtdlbl;
    private javax.swing.JLabel save;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JTextField txtCH;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDI;
    private javax.swing.JTextField txtDT;
    private javax.swing.JTextField txtNC;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtQ;
    // End of variables declaration//GEN-END:variables
}
