/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Malu Passo Silva
 */
import conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.SQLException;

public class Professor extends javax.swing.JFrame {

    Conexao con_cliente;
    
    public Professor() {
        
        con_cliente = new Conexao();
        con_cliente.conecta();
        con_cliente.executaSQL("select * from professor order by IdProfessor"); 
        
        initComponents();
        
        professor.setAutoCreateRowSorter(true);
        preencherTabela();
        posicionarRegistro();
    }

    public void preencherTabela(){
        
        professor.getColumnModel().getColumn(0).setPreferredWidth(10);
        professor.getColumnModel().getColumn(1).setPreferredWidth(70);
        professor.getColumnModel().getColumn(2).setPreferredWidth(70);
        professor.getColumnModel().getColumn(3).setPreferredWidth(10);
        professor.getColumnModel().getColumn(4).setPreferredWidth(70);
        professor.getColumnModel().getColumn(5).setPreferredWidth(70);
        professor.getColumnModel().getColumn(6).setPreferredWidth(70);
        professor.getColumnModel().getColumn(7).setPreferredWidth(50);
        professor.getColumnModel().getColumn(8).setPreferredWidth(70);
        
        DefaultTableModel modelo = (DefaultTableModel) professor.getModel();
        modelo.setNumRows(0);
        
        try{
            
            con_cliente.resultset.beforeFirst();
            
            while(con_cliente.resultset.next()){
                
                modelo.addRow(new Object[]{
                    
                    con_cliente.resultset.getString("IdProfessor"), con_cliente.resultset.getString("NomeProf"), con_cliente.resultset.getString("PDataNasc"),
                    con_cliente.resultset.getString("PGenero"), con_cliente.resultset.getString("PEndereco"), con_cliente.resultset.getString("PTelefone"), 
                    con_cliente.resultset.getString("ProfEmail"), con_cliente.resultset.getString("ValorHoraAula"), con_cliente.resultset.getString("DataContrato")
                        
                });
                       
            }
              
        }
          
        catch(SQLException erro){
                
            JOptionPane.showMessageDialog(null, "\n Erro ao listar dados da tabela!! :\n" + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);    
                
        }   
            
    }
    
    public void posicionarRegistro(){
        
        try{
            
            con_cliente.resultset.first();
            mostrar_Dados();
            
        }
        
        catch(SQLException erro){
            
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    public void mostrar_Dados(){
        
        try{
            
            txtCod.setText(con_cliente.resultset.getString("IdProfessor"));
            txtNome.setText(con_cliente.resultset.getString("NomeProf"));
            txtDataNasc.setText(con_cliente.resultset.getString("PDataNasc"));
            txtGen.setText(con_cliente.resultset.getString("PGenero"));
            txtEndereco.setText(con_cliente.resultset.getString("PEndereco"));
            txtTel.setText(con_cliente.resultset.getString("PTelefone"));
            txtEmail.setText(con_cliente.resultset.getString("ProfEmail"));
            txtVHA.setText(con_cliente.resultset.getString("ValorHoraAula"));
            txtDataCon.setText(con_cliente.resultset.getString("DataContrato"));
            
        }
        
        catch(SQLException erro){
            
            JOptionPane.showMessageDialog(null, "Não localizou dados: "+erro, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        backbtn = new javax.swing.JLabel();
        prof_lbl = new javax.swing.JLabel();
        prof_image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nome_lbl = new javax.swing.JLabel();
        datanasc_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDataNasc = new javax.swing.JTextField();
        txtGen = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtVHA = new javax.swing.JTextField();
        txtDataCon = new javax.swing.JTextField();
        PrimeiroRegistro = new javax.swing.JLabel();
        VoltarUmRegistro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        professor = new javax.swing.JTable();
        ProximoRegistro = new javax.swing.JLabel();
        UltimoRegistro = new javax.swing.JLabel();
        Delete_btn = new javax.swing.JLabel();
        save_btn = new javax.swing.JLabel();
        edit_btn = new javax.swing.JLabel();
        criar_btn = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1005, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1005, 820));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        backbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fasticon-Essential-Toolbar-Undo.32.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });

        prof_lbl.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        prof_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prof_lbl.setText("Professor");

        prof_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prof_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teacher.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel1.setText("Código:");

        nome_lbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        nome_lbl.setText("Nome:");

        datanasc_lbl.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        datanasc_lbl.setText("Data de nascimento:");

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel4.setText("Gênero:");

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel5.setText("Endereço:");

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel6.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel7.setText("E-mail:");

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel8.setText("Valor Hora/Aula:");

        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel9.setText("Data de contratação: ");

        txtCod.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtCod.setToolTipText("Inserir o código");

        txtNome.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtNome.setToolTipText("Inserir o nome");

        txtDataNasc.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtDataNasc.setToolTipText("Inserir a data de nascimento");

        txtGen.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtGen.setToolTipText("Inserir o gênero ");

        txtEndereco.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtEndereco.setToolTipText("Inserir o endereço");

        txtTel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtTel.setToolTipText("Inserir o telefone");

        txtEmail.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtEmail.setToolTipText("Inserir e-mail");

        txtVHA.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtVHA.setToolTipText("Insira o valor hora/aula");

        txtDataCon.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtDataCon.setToolTipText("Inserir a data de contratação");

        PrimeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-rew.48.png"))); // NOI18N
        PrimeiroRegistro.setToolTipText("Ir para o primeiro registro");
        PrimeiroRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrimeiroRegistroMouseClicked(evt);
            }
        });

        VoltarUmRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VoltarUmRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-back.48.png"))); // NOI18N
        VoltarUmRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarUmRegistroMouseClicked(evt);
            }
        });

        professor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data de nascimento", "Gênero", "Endereço", "Telefone", "E-mail", "Valor hora/aula", "Data de contratação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        professor.setToolTipText("Tabela com os professores registrados");
        professor.setPreferredSize(new java.awt.Dimension(135, 80));
        professor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                professorMouseClicked(evt);
            }
        });
        professor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                professorKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(professor);
        if (professor.getColumnModel().getColumnCount() > 0) {
            professor.getColumnModel().getColumn(0).setResizable(false);
            professor.getColumnModel().getColumn(1).setResizable(false);
            professor.getColumnModel().getColumn(2).setResizable(false);
            professor.getColumnModel().getColumn(3).setResizable(false);
            professor.getColumnModel().getColumn(4).setResizable(false);
            professor.getColumnModel().getColumn(5).setResizable(false);
            professor.getColumnModel().getColumn(6).setResizable(false);
            professor.getColumnModel().getColumn(7).setResizable(false);
            professor.getColumnModel().getColumn(8).setResizable(false);
        }

        ProximoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProximoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-fordward.48.png"))); // NOI18N
        ProximoRegistro.setToolTipText("Ir para o próximo registro");
        ProximoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProximoRegistroMouseClicked(evt);
            }
        });

        UltimoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Player-ff.48.png"))); // NOI18N
        UltimoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UltimoRegistroMouseClicked(evt);
            }
        });

        Delete_btn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Creative-Freedom-Free-Funktional-02-Recycle.48.png"))); // NOI18N
        Delete_btn.setToolTipText("Deletar registro");
        Delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_btnMouseClicked(evt);
            }
        });

        save_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Floppy-disk.48.png"))); // NOI18N
        save_btn.setToolTipText("Salvar registro");
        save_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_btnMouseClicked(evt);
            }
        });

        edit_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Pencil-yellow.48.png"))); // NOI18N
        edit_btn.setToolTipText("Editar o registro");
        edit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_btnMouseClicked(evt);
            }
        });

        criar_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Emey87-Trainee-Badge-plus.48.png"))); // NOI18N
        criar_btn.setToolTipText("Criar um novo registro");
        criar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criar_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prof_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(prof_image, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nome_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(datanasc_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGen, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVHA, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataCon, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(PrimeiroRegistro)
                                    .addGap(18, 18, 18)
                                    .addComponent(VoltarUmRegistro)
                                    .addGap(18, 18, 18)
                                    .addComponent(ProximoRegistro)
                                    .addGap(18, 18, 18)
                                    .addComponent(UltimoRegistro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(criar_btn)
                                    .addGap(18, 18, 18)
                                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(save_btn)
                                    .addGap(18, 18, 18)
                                    .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(prof_lbl)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_lbl)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datanasc_lbl)
                            .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(prof_image, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtVHA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDataCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_btn)
                    .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_btn)
                    .addComponent(criar_btn)
                    .addComponent(VoltarUmRegistro)
                    .addComponent(ProximoRegistro)
                    .addComponent(UltimoRegistro)
                    .addComponent(PrimeiroRegistro))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        
        //Abrir a tela do curso e fechar a tela de menu.
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_backbtnMouseClicked

    private void PrimeiroRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrimeiroRegistroMouseClicked
        
        try{
            con_cliente.resultset.first();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_PrimeiroRegistroMouseClicked

    private void VoltarUmRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarUmRegistroMouseClicked
        
        try{
            con_cliente.resultset.previous();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o registro anterior: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_VoltarUmRegistroMouseClicked

    private void professorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_professorMouseClicked
        
        //Evento para o clique do mouse sobre o registro da tabela:
        int linha_selecionada = professor.getSelectedRow();
        txtCod.setText(professor.getValueAt(linha_selecionada, 0).toString());
        txtNome.setText(professor.getValueAt(linha_selecionada, 1).toString());
        txtDataNasc.setText(professor.getValueAt(linha_selecionada, 2).toString());
        txtGen.setText(professor.getValueAt(linha_selecionada, 3).toString());
        txtEndereco.setText(professor.getValueAt(linha_selecionada, 4).toString());
        txtTel.setText(professor.getValueAt(linha_selecionada, 5).toString());
        txtEmail.setText(professor.getValueAt(linha_selecionada, 6).toString());
        txtVHA.setText(professor.getValueAt(linha_selecionada, 7).toString());
        txtDataCon.setText(professor.getValueAt(linha_selecionada, 8).toString());
        
    }//GEN-LAST:event_professorMouseClicked

    private void professorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_professorKeyPressed
        
        //Evento para o clique do mouse sobre o registro da tabela:
        int linha_selecionada = professor.getSelectedRow();
        txtCod.setText(professor.getValueAt(linha_selecionada, 0).toString());
        txtNome.setText(professor.getValueAt(linha_selecionada, 1).toString());
        txtDataNasc.setText(professor.getValueAt(linha_selecionada, 2).toString());
        txtGen.setText(professor.getValueAt(linha_selecionada, 3).toString());
        txtEndereco.setText(professor.getValueAt(linha_selecionada, 4).toString());
        txtTel.setText(professor.getValueAt(linha_selecionada, 5).toString());
        txtEmail.setText(professor.getValueAt(linha_selecionada, 6).toString());
        txtVHA.setText(professor.getValueAt(linha_selecionada, 7).toString());
        txtDataCon.setText(professor.getValueAt(linha_selecionada, 8).toString());
        
    }//GEN-LAST:event_professorKeyPressed

    private void ProximoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProximoRegistroMouseClicked
       
        try{
            con_cliente.resultset.next();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_ProximoRegistroMouseClicked

    private void UltimoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UltimoRegistroMouseClicked
        
        try{
            con_cliente.resultset.last();
            mostrar_Dados();
        }
        
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro: " + erro, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_UltimoRegistroMouseClicked

    private void Delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_btnMouseClicked
        
        String sql = "";
        
        try{
            
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar exclusão", JOptionPane.YES_NO_OPTION, 3);
            
            if(resposta == 0){
                
                sql = "delete from professor where IdProfessor = " + txtCod.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                
                if(excluir == 1){
                    
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from professor order by IdProfessor");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                    
                }
                
                else{
                    
                    JOptionPane.showMessageDialog(null, "Operação cancela pelo usuário!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                    
                }
            }
        }
        
        catch(SQLException excecao){
            
            JOptionPane.showMessageDialog(null, "Erro na exclusão: "  + excecao, "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_Delete_btnMouseClicked

    private void save_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_btnMouseClicked
        
        //Criando strings para armazenar os dados digitados nos campos de texto
        String codigo = txtCod.getText();
        String nome = txtNome.getText();
        String datanasc = txtDataNasc.getText();
        String genero = txtGen.getText();
        String endereco = txtEndereco.getText();
        String telefone = txtTel.getText();
        String email = txtEmail.getText();
        String valorha = txtVHA.getText();
        String datacon = txtDataCon.getText();
        
        //
        try{
            
            String insert_sql = "insert into professor (IdProfessor, NomeProf, PDataNasc, PGenero, PEndereco, PTelefone, ProfEmail, ValorHoraAula, DataContrato) values ('" + 
            codigo + "', '" + nome + "', '" + datanasc + "', '" + genero + "', '" + endereco + "', '" + telefone + "', '" + email + "', '" + valorha + "', '" + datacon + "')";
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!", "Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from professor order by IdProfessor");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();
            
        }
        
        catch(SQLException errosql){
            
            JOptionPane.showMessageDialog(null, "Erro de gravação :\n " + errosql, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_save_btnMouseClicked

    private void criar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criar_btnMouseClicked
        
        //Limpa as caixas de texto
        txtCod.setText("");
        txtNome.setText("");
        txtDataNasc.setText("");
        txtGen.setText("");
        txtEndereco.setText("");
        txtTel.setText("");
        txtEmail.setText("");
        txtVHA.setText("");
        txtDataCon.setText("");
        
    }//GEN-LAST:event_criar_btnMouseClicked

    private void edit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_btnMouseClicked
        
        //Criando strings para armazenar os dados digitados nos campos de texto
        String nome = txtNome.getText();
        String datanasc = txtDataNasc.getText();
        String genero = txtGen.getText();
        String endereco = txtEndereco.getText();
        String telefone = txtTel.getText();
        String email = txtEmail.getText();
        String valorha = txtVHA.getText();
        String datacon = txtDataCon.getText();

        //
        String sql = "";
        
        //
        String msg = "";
        
        try{
            
            if(txtCod.getText().equals("")){
                
                sql = "insert into professor (NomeProf, PDataNasc, PGenero, PEndereco, PTelefone, ProfEmail, ValorHoraAula, DataContrato) values (" + nome 
                        + "', '" + datanasc + "', '" + genero + "', '" + endereco + "', '" +  telefone + "', '" + email + "', '" + valorha + "', '" +
                        datacon + "' where IdProfessor = " + txtCod.getText();
                
                msg = "Gravação de um novo registro";
            
            }
            
            else{
                
                sql = "update professor set NomeProf = '" + nome + "', PDataNasc = '" + datanasc + "', PGenero = '" + genero + "', PEndereco = '" + endereco 
                        + "', PTelefone = '" + telefone + "', ProfEmail = '" + email + "', ValorHoraAula = '" + valorha + "', DataContrato = '" + datacon +
                        "' where IdProfessor = " + txtCod.getText();
                
                msg = "Alteração de registro ";
            
            }
            
            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, msg + "realizada com sucesso!", "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
            
            con_cliente.executaSQL("select * from professor order by IdProfessor");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();
        }
        
        catch(SQLException errosql){
            
            JOptionPane.showMessageDialog(null, "Erro de gravação :\n " + errosql, "Mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_edit_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete_btn;
    private javax.swing.JLabel PrimeiroRegistro;
    private javax.swing.JLabel ProximoRegistro;
    private javax.swing.JLabel UltimoRegistro;
    private javax.swing.JLabel VoltarUmRegistro;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel criar_btn;
    private javax.swing.JLabel datanasc_lbl;
    private javax.swing.JLabel edit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nome_lbl;
    private javax.swing.JLabel prof_image;
    private javax.swing.JLabel prof_lbl;
    private javax.swing.JTable professor;
    private javax.swing.JLabel save_btn;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDataCon;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtGen;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtVHA;
    // End of variables declaration//GEN-END:variables
}
